name: Start application
description: Once done, the application is ready on `localhost:80`.
runs:
  using: composite
  steps:
    - name: Get frontend build
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: Prototypes/POC-Prototype1/dist

    - name: Get samples
      uses: actions/download-artifact@v4
      with:
        name: samples
        path: Prototypes/POC-Prototype1/public
        
    - name: Start containers
      run: |
        cd Prototypes/POC-Prototype1
        export COUCHDB_USER="admin"
        export COUCHDB_PASSWORD="mypassword"
        docker compose up --detach
      shell: bash
    
    - name: Wait for frontend
      uses: docker://benel/wait-for-response:1
      with:
        args: http://localhost/ 200 30000 500